version: '3.3'

services:
  nextjs:
    environment:
      SECRET_COOKIE_PASSWORD: MXsFaEe5YO76opTRTuMcDHzMy5H7d68TS0V2XLeQKKv8bukHwZAkSv2nm0sY7s7t
      # Need this env var for windows hot module reloading
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 4000:3000
    build:
      context: .
      dockerfile: ./docker/local.dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - nestjs
  nestjs:
    ports:
      - 9001:3000
    build:
      context: ./backend
      dockerfile: ./dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      # - /usr/src/app/dist
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27018:27017'
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
